global:
  scrape_interval: 15s

scrape_configs:
  - job_name: api-gateway
    static_configs:
      - targets: [ 'api-gateway:8080' ]
    metrics_path: /actuator/prometheus

  - job_name: auth-service
    static_configs:
      - targets: [ 'auth-service:8081' ]
    metrics_path: /actuator/prometheus

  - job_name: example-under-armor-service
    static_configs:
      - targets: [ 'example-under-armor-service:8082' ]
    metrics_path: /actuator/prometheus

















