spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: auth-swagger-ui
            uri: http://auth-service:8081
            predicates:
              - name: Path
                args:
                  pattern: /auth/swagger-ui/**
            filters:
              - name: StripPrefix
                args:
                  parts: 1
          - id: auth-api-docs
            uri: http://auth-service:8081
            predicates:
              - name: Path
                args:
                  pattern: /auth/v3/api-docs/**
            filters:
              - name: StripPrefix
                args:
                  parts: 1
          - id: auth-service
            uri: http://auth-service:8081
            predicates:
              - name: Path
                args:
                  pattern: /auth/**
        default-filters:
          - name: DedupeResponseHeader
            args:
              name: Access-Control-Allow-Credentials Access-Control-Allow-Origin
server:
  port: 8080
logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: INFO
    org.springframework.web: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true
  prometheus:
    metrics:
      export:
        enabled: true
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4318/v1/traces}